sudo: required

script:
  - sudo docker run --user $(id -u):$(id -g) --rm -v $(pwd)/:/build/ -w /build/ archlinux makepkg

after_success:
  - wget -q https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - export UPLOADTOOL_SUFFIX=$TRAVIS_BRANCH
  - bash upload.sh *.tar.*

branches:
  except:
    - "/^(?i:continuous.*)$/"

notifications:
  email: false
